---
- name: Install Apache on EC2
  hosts: localhost
  tasks:
    - name: Install Apache
      shell: sudo apt install apache2 -y

    - name: Start Apache
      shell: sudo systemctl start apache2

    - name: Enable Apache
      shell: sudo systemctl enable apache2